settings:
  title: 'Status Page'
  url: 'https://status.financiatec.co' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www.financiacapital.cl # unique identifier
    name: www.financiacapital.cl
    url: 'https://www.financiacapital.cl/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: www.financiatec.cl
    name: www.financiatec.cl
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.financiatec.cl'
    method: GET
    expectStatus: 200

  - id: fcintranet
    name: FC Intranet API
    url: 'https://www.financiatec.cl/fcintranet'
    method: GET
    expectStatus: 200

  - id: FC Admin
    name: FC Admin
    url: 'https://admin.financiatec.cl/'
    method: GET
    expectStatus: 200

  - id: FinanciaPress
    name: FinanciaPress
    url: 'https://landing.financiatec.cl/'
    method: GET
    expectStatus: 200