name = "cf-workers-status-page"
workers_dev = true
account_id = "bb8c914ce999f8e1fab00372e402d54c"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
zone_id="982596ae593eabad86230855fc78a48c"

[triggers]
crons = ["*/3 * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="29d11f6611cf4bfd9f5d54d07b801373"}]
#[[kv_namespaces]]
#binding = "KV_STATUS_PAGE"
#id = "29d11f6611cf4bfd9f5d54d07b801373"
[env]
    [env.production]
        route="https://status.financiatec.co"
        [[env.production.kv_namespaces]]
            binding = "KV_STATUS_PAGE"
            id = "29d11f6611cf4bfd9f5d54d07b801373"