name = "cf-workers-status-page"
workers_dev = true
account_id = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"

[triggers]
crons = ["*/3 * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
[env.production]
kv-namespaces = [{binding="KV_STATUS_PAGE", id="29d11f6611cf4bfd9f5d54d07b801373"}]
zone_id="982596ae593eabad86230855fc78a48c"
route="https://status.financiatec.co"
